routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('tasks',\App\Http\Controllers\TaskController::class);
Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class]);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $table ='post';
    protected $fillable=[
      'name',
      'body',
    ];

}

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $table= 'tasks' ;
    protected $fillable =[ 'name', 'content'];

}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/API/PostController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Http\Resources\PostCollection;
use App\Http\Resources\PostRource;
use App\Models\Post;

class PostController extends Controller
{
    protected $post;
    public function __construct(Post $post)
    {
        $this->post=$post;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {

        $posts =$this->post->paginate(5);
        $postCollection= new PostCollection($posts);

        return $this-> senSucessResponse($postCollection , 'success', \Illuminate\Http\Response::HTTP_OK);
    }
    /**
     * Store a newly created resource in storage.
     */
    public function store( StorePostRequest $request)
    {
        $dataCreat= $request ->all();
        $post = $this -> post -> create($dataCreat);
        $postResource = new PostRource($post);
        return $this-> senSucessResponse($postResource , 'success', \Illuminate\Http\Response::HTTP_OK);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $post = $this -> post -> findOrFail($id);
        $postResource = new PostRource($post);
        return $this-> senSucessResponse($postResource, 'success', \Illuminate\Http\Response::HTTP_OK);

    }

    /**
     * Update the specified resource in storage.
     */
    public function update( UpdatePostRequest $request, string $id)
    {
        $post = $this -> post -> findOrFail($id);
        $dataUpdate =$request -> all();
        $post ->update($dataUpdate);
        $postResource = new PostRource($post);
        return $this-> senSucessResponse($postResource, 'update success', \Illuminate\Http\Response::HTTP_OK);

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $post = $this -> post -> findOrFail($id);
        $post ->delete();
        $postResource = new PostRource($post);
        return $this-> senSucessResponse($postResource, 'delete success', \Illuminate\Http\Response::HTTP_OK);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use http\Message;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;

   public function senSucessResponse($data ='', $message ='success', $status =200){
       return \response()->json([
           'data'=>$data,
           'message'=>$message,
       ],$status);

   }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\CreateTaskRequest;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\StoreTaskRequest;
use App\Http\Requests\UpdatePutTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Http\Resources\TaskResource;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Http\Request;
use App\Models\Task;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Tests\Feature\Tasks\StoreTaskTest;

class TaskController extends Controller
{
    protected $task;

    public function __construct(Task $task)
    {
        $this->task= $task ;
    }

    public function index()
    {
//        $tasks=$this->task->all();
        $tasks = Task::paginate(10);
        return view('tasks.index', compact('tasks'));
    }
    public function store(  StoreTaskRequest $request)
    {
         $task=$this->task->create($request->all());
        return redirect()->route('tasks.index');

    }
    public function create(){
        return \view('tasks.create');
    }
    public function update(  UpdateTaskRequest $request, $id){
        $task =$this->task-> findOrFail($id);
        $task->update($request->all());
        return redirect()->route('tasks.index');
    }
    public function destroy( $id){
        $this->task->destroy($id);
        return redirect()->route('tasks.index');

    }
    public function edit($id ){
        $task=$this->task->findOrFail($id);
        return \view('tasks.edit', compact('task'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Dashboard') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        {{ __('You are logged in!') }}
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Logout') }}
                                </button>
{{--                                <button type="tasks" class="btn btn-primary">--}}
{{--                                    {{ route('tasks.index}}--}}
{{--                                </button>--}}
                            </form>
                            <a href="{{route('tasks.index')}}">tasks</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
@yield('content')

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content') <!-- Provide a section name, in this case, 'content' -->
<div class="container">
    <div class="row justify-content-center" >
        <div class="col-md-8">
            <h2> Create-Task</h2>
            <form action="{{route('tasks.store')}}" method="POST">
                @csrf
                <input type="text" class="form-group" name="name" placeholder="Name..." >
                <input type="text" class="form-group" name="content" placeholder="Content...">
                <button class = "btn btn-success" > Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2>Edit Task</h2>
                <form action="{{ route('tasks.update', ['task' => $task->id]) }}" method="POST">
                    @csrf
                    @method('PUT')

                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{ $task->name }}">
                    </div>

                    <div class="form-group">
                        <label for="content">Content:</label>
                        <textarea class="form-control" id="content" name="content">{{ $task->content }}</textarea>
                    </div>

                    <button type="submit" class="btn btn-success">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content') <!-- Provide a section name, in this case, 'content' -->
<div class="container">
    <div class="row justify-content-center" >
        <a href="{{ route('tasks.create') }}" class="btn   btn-dark" >create</a>
        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Content</th>
            </tr>
            @foreach($tasks as $task)
                <tr>
                    <td>{{ $task->id }}</td>
                    <td>{{ $task->name }}</td>
                    <td>{{ $task->content }}</td>
                    <td>
                        <form method='post' action="{{route('tasks.destroy', $task->id)}}">
                            @csrf
                            @method('delete')
                            <button class="btn btn-danger"> Delete</button>
                            <a href="{{route('tasks.edit' , $task->id)}}" class="btn btn-warning"> Edit </a>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
        {{$tasks->links()}}
    </div>
</div>
@endsection

resources/views/tasks/search.blade.php
<?php